pipeline {
    agent any

    environment {
        // Jenkins Credential로 등록된 .env 파일 ID
        ENV_FILE_ID = '5d372d81-243b-470a-8f36-7c8e9f849681'
        // Git 관련 환경변수
        GIT_CREDENTIALS_ID = '9b618287-83a8-468a-84f1-57a90cdc7438'
        GIT_REPO_URL = 'https://lab.ssafy.com/s13-webmobile1-sub1/S13P11A605.git'
        GIT_BRANCH = 'master'
    }

    stages {
        stage('Clone') {
            steps {
                git credentialsId: "${GIT_CREDENTIALS_ID}", url: "${GIT_REPO_URL}", branch: "${GIT_BRANCH}"
            }
        }

        stage('Setup Secrets') {
            steps {
                // Jenkins Credential에 등록한 .env 파일을 작업공간에 복사
                withCredentials([file(credentialsId: "${ENV_FILE_ID}", variable: 'ENV_FILE')]) {
                    sh '''
                        cp "$ENV_FILE" .env
                        chmod 644 .env
                    '''
                }
            }
        }

        stage('Build') {
            steps {
                // 빌드 필요시 gradle 빌드 등 수행 (원하면)
                sh '''
                    chmod +x gradlew
                    ./gradlew clean build -x test --no-daemon
                    cp build/libs/nearzoom-0.0.1-SNAPSHOT.jar app.jar
                '''
            }
        }

        stage('Docker Compose Up') {
            steps {
                // docker compose로 모든 컨테이너 띄우기
                sh '''
                    cd $WORKSPACE
                    docker compose down || true
                    docker compose up -d --jenkins
                    docker compose ps
                '''
            }
        }
    }
}
